### ISSUE TITLE
v1.4.1 Release

### ISSUE THREAD

**Issue by patrick-ogrady** [coinbase/rosetta-specifications#28]
- [x] Add `Coin` Model for UTXO Tracking ( `Identifier` as string + CoinAction[create,spend])...do we need to create `CoinIdentifier`?)...optionally allow for returning Coins in `/account/balance` response: identifier + amount (#30)
- [x] Optionally Report Syncing Status (#27) ... will need to clarify wording around what `current_block_identifier` is vs `syncing_block_identifier`... should also clarify that it is completely informational
- [x] Unify `TransactionIdentifierResponse` for `/construction/submit` and `/construction/hash` (#29 )
- [x] Use 500 for all non-200 (#29 )
- [x] Update version to `v.1.4.1` (#29)
